package models

import "go.mongodb.org/mongo-driver/bson/primitive"

// CaseAttachment is an auxiliary file attached to a case (Task) that is
// NOT part of the video pipeline: PDFs, hi-res photos, scanned
// documents, audio notes, etc. Unlike CaseMedia, attachments are
// uploaded synchronously by the API in response to a user action, are
// never mutated by background workers, and have no version chain.
//
// Attachments are embedded directly on Task (Task.Attachments) on the
// assumption that the cardinality stays bounded per case (target soft
// cap ~100). Only metadata is stored — the file bytes themselves live
// in Vault and are referenced through File / Provider, matching the
// pattern used by CaseMedia and the worker pipelines.
//
// If the cardinality assumption ever stops holding the migration path
// is a one-shot $unwind + $out into a dedicated case_attachments
// collection; nothing about this shape blocks that.
type CaseAttachment struct {
	Id primitive.ObjectID `json:"id" bson:"_id,omitempty"`

	// Kind is a coarse classification of the attachment used by the UI
	// to pick an icon / viewer. MimeType is the source of truth for
	// content negotiation; Kind is derived from it at upload time.
	Kind     CaseAttachmentKind `json:"kind" bson:"kind"`
	MimeType string             `json:"mimeType" bson:"mime_type"`

	// Name is the original filename at upload time. Users may rename
	// the attachment afterwards without renaming the underlying object
	// in Vault.
	Name string `json:"name" bson:"name"`

	// Size in bytes of the stored object. Useful for UI display and
	// for sanity-checking that the Vault object still matches what we
	// recorded.
	Size int64 `json:"size,omitempty" bson:"size,omitempty"`

	// Sha256 is the hex-encoded SHA-256 of the uploaded bytes,
	// computed by hub-api while streaming the upload to Vault. Used
	// for de-duplication detection and integrity checks on large
	// files. Optional — older entries may not have it.
	Sha256 string `json:"sha256,omitempty" bson:"sha256,omitempty"`

	// Storage pointer into Vault (same abstraction as CaseMedia.File /
	// CaseMedia.Provider). Provider identifies the storage solution;
	// File is the object key inside it.
	File     string `json:"file" bson:"file"`
	Provider string `json:"provider" bson:"provider"`

	// Optional derived preview generated by hub-api on upload (a
	// downscaled JPEG for images, the first page rendered to an image
	// for PDFs, etc.). Absence is fine — the UI falls back to a
	// kind-based icon.
	ThumbnailFile     string `json:"thumbnailFile,omitempty" bson:"thumbnail_file,omitempty"`
	ThumbnailProvider string `json:"thumbnailProvider,omitempty" bson:"thumbnail_provider,omitempty"`

	// RelatedCaseMediaId optionally links the attachment to a specific
	// case_media entry it documents or annotates (for example, an
	// annotated screenshot of a redacted clip). Nil for free-standing
	// case-level attachments.
	RelatedCaseMediaId *primitive.ObjectID `json:"relatedCaseMediaId,omitempty" bson:"related_case_media_id,omitempty"`

	CreatedAt int64  `json:"createdAt,omitempty" bson:"created_at,omitempty"`
	CreatedBy string `json:"createdBy,omitempty" bson:"created_by,omitempty"`
	UpdatedAt int64  `json:"updatedAt,omitempty" bson:"updated_at,omitempty"`

	// Url / ThumbnailUrl are signed by hub-api at fetch time and never
	// persisted. They should be excluded from list-cases projections
	// to keep that endpoint light.
	Url          string `json:"url,omitempty" bson:"-"`
	ThumbnailUrl string `json:"thumbnailUrl,omitempty" bson:"-"`
}

// CaseAttachmentKind is a coarse classification driving icon / viewer
// selection in the UI. Derived from MimeType at upload time by hub-api.
type CaseAttachmentKind string

const (
	CaseAttachmentKindPDF      CaseAttachmentKind = "pdf"
	CaseAttachmentKindImage    CaseAttachmentKind = "image"
	CaseAttachmentKindDocument CaseAttachmentKind = "document" // docx, odt, txt, ...
	CaseAttachmentKindAudio    CaseAttachmentKind = "audio"
	CaseAttachmentKindVideo    CaseAttachmentKind = "video" // user-supplied, NOT pipeline output
	CaseAttachmentKindOther    CaseAttachmentKind = "other"
)
