// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// AccessToken property field names (BSON)
const (
	AccessTokenId = "_id"
	AccessTokenName = "name"
	AccessTokenDescription = "description"
	AccessTokenExpiration = "expiration"
	AccessTokenScopes = "scopes"
	AccessTokenToken = "token"
	AccessTokenOrganisationId = "organisationId"
	AccessTokenUserId = "userId"
	AccessTokenAudit = "audit"
)
