// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Activity property field names (BSON)
const (
	ActivityDay = "day"
	ActivityRequests = "requests"
	ActivityVideos = "videos"
	ActivityImages = "images"
	ActivityUsage = "usage"
	ActivityTimestamp = "timestamp"
	ActivityDevices = "devices"
)
