// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// AlertFeatures property field names (BSON)
const (
	AlertFeaturesCreateMarker = "createMarker"
)

// CustomAlert property field names (BSON)
const (
	CustomAlertId = "_id"
	CustomAlertEnabled = "enabled"
	CustomAlertTitle = "title"
	CustomAlertDescription = "description"
	CustomAlertChannelsAll = "channelsAll"
	CustomAlertChannelsList = "channelsList"
	CustomAlertDevicesAll = "devicesAll"
	CustomAlertDevicesList = "devicesList"
	CustomAlertCountingDevicesAll = "countingDevicesAll"
	CustomAlertCountingDevicesList = "countingDevicesList"
	CustomAlertClassificationAll = "classificationAll"
	CustomAlertClassificationList = "classificationList"
	CustomAlertTimeAdvanced = "timeAdvanced"
	CustomAlertTimeRange1Max = "timeRange1Max"
	CustomAlertTimeRange1Min = "timeRange1Min"
	CustomAlertTimeRange2Max = "timeRange2Max"
	CustomAlertTimeRange2Min = "timeRange2Min"
	CustomAlertUserId = "user_id"
	CustomAlertMasterUserId = "master_user_id"
	CustomAlertEmailEmail = "email_email"
	CustomAlertSlackHook = "slack_hook"
	CustomAlertSlackBotname = "slack_botname"
	CustomAlertPushbulletApikey = "pushbullet_apikey"
	CustomAlertTelegramToken = "telegram_token"
	CustomAlertTelegramChannel = "telegram_channel"
	CustomAlertAlexaToken = "alexa_token"
	CustomAlertWebhookUrl = "webhook_url"
	CustomAlertIftttToken = "ifttt_token"
	CustomAlertSMSAccountsid = "sms_accountsid"
	CustomAlertSMSAuthtoken = "sms_authtoken"
	CustomAlertSMSTelfrom = "sms_telfrom"
	CustomAlertSMSTelto = "sms_telto"
	CustomAlertPushoverApikey = "pushover_apikey"
	CustomAlertPushoverSendto = "pushover_sendto"
	CustomAlertMotionRegions = "motionRegions"
	CustomAlertCountingLines = "countingLines"
	CustomAlertInputList = "inputList"
	CustomAlertInputsAND = "inputsAND"
	CustomAlertOutputList = "outputList"
	CustomAlertFeatures = "features"
)
