// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Analysis property field names (BSON)
const (
	AnalysisClassify = "classify"
	AnalysisCounting = "counting"
	AnalysisDominantColor = "dominantcolor"
	AnalysisThumby = "thumby"
	AnalysisSprite = "sprite"
	AnalysisFaceRedaction = "faceRedaction"
)

// AnalysisFilter property field names (BSON)
const (
	AnalysisFilterStart = "start"
	AnalysisFilterLimit = "limit"
	AnalysisFilterSort = "sort"
	AnalysisFilterOperations = "operations"
)

// AnalysisShort property field names (BSON)
const (
	AnalysisShortId = "_id"
	AnalysisShortProvider = "provider"
	AnalysisShortSource = "source"
	AnalysisShortFileUrl = "src"
)

// AnalysisWrapper property field names (BSON)
const (
	AnalysisWrapperId = "_id"
	AnalysisWrapperOrganisationId = "organisationId"
	AnalysisWrapperProjectId = "projectId"
	AnalysisWrapperProvider = "provider"
	AnalysisWrapperSource = "source"
)

// Classify property field names (BSON)
const (
	ClassifyProperties = "properties"
	ClassifyDetails = "details"
)

// ClassifyDetails property field names (BSON)
const (
	ClassifyDetailsId = "id"
	ClassifyDetailsX = "x"
	ClassifyDetailsY = "y"
	ClassifyDetailsW = "w"
	ClassifyDetailsH = "h"
	ClassifyDetailsFrameWidth = "frameWidth"
	ClassifyDetailsFrameHeight = "frameHeight"
	ClassifyDetailsMeanColor = "meanColor"
	ClassifyDetailsFrame = "frame"
	ClassifyDetailsOccurence = "occurence"
	ClassifyDetailsDistance = "distance"
	ClassifyDetailsValid = "valid"
	ClassifyDetailsClassified = "classified"
	ClassifyDetailsTraject = "traject"
	ClassifyDetailsColorString = "colorStr"
	ClassifyDetailsIsStatic = "isStatic"
	ClassifyDetailsFrames = "frames"
	ClassifyDetailsStaticDistance = "staticDistance"
	ClassifyDetailsTrajectCentroids = "trajectCentroids"
)

// Color property field names (BSON)
const (
	ColorName = "name"
	ColorCount = "count"
)

// Counting property field names (BSON)
const (
	CountingRecords = "records"
)

// CountingDetail property field names (BSON)
const (
	CountingDetailDeviceID = "deviceId"
	CountingDetailObjectName = "objectName"
	CountingDetailTimestamp = "timestamp"
	CountingDetailVideoWidth = "videoWidth"
	CountingDetailVideoHeight = "videoHeight"
	CountingDetailSegment = "segment"
	CountingDetailObjectId = "objectId"
	CountingDetailPosition = "position"
)

// CountingRecord property field names (BSON)
const (
	CountingRecordType = "type"
	CountingRecordSegmentId = "segmentId"
	CountingRecordUsername = "username"
	CountingRecordAlertId = "alert_id"
	CountingRecordAlertName = "alert_name"
	CountingRecordTimestamp = "timestamp"
	CountingRecordDeviceId = "deviceId"
	CountingRecordObjectName = "objectName"
	CountingRecordCount = "count"
	CountingRecordDuration = "duration"
)

// DetectionCategory property field names (BSON)
const (
	DetectionCategoryId = "id"
	DetectionCategoryName = "name"
	DetectionCategoryAlias = "alias"
)

// DetectionMedia property field names (BSON)
const (
	DetectionMediaWidth = "width"
	DetectionMediaHeight = "height"
	DetectionMediaFps = "fps"
	DetectionMediaFrameCount = "frameCount"
	DetectionMediaRotation = "rotation"
)

// DetectionRun property field names (BSON)
const (
	DetectionRunId = "_id"
	DetectionRunKey = "key"
	DetectionRunOrganisationId = "organisationId"
	DetectionRunProjectId = "projectId"
	DetectionRunDeviceId = "deviceId"
	DetectionRunTask = "task"
	DetectionRunSource = "source"
	DetectionRunSchemaVersion = "schemaVersion"
	DetectionRunMedia = "media"
	DetectionRunCategories = "categories"
	DetectionRunTracks = "tracks"
	DetectionRunOriginalCoordinateSpace = "originalCoordinateSpace"
	DetectionRunOriginalBoxForm = "originalBoxForm"
	DetectionRunCreatedAt = "createdAt"
	DetectionRunUpdatedAt = "updatedAt"
	DetectionRunRecordingTimestamp = "recordingTimestamp"
)

// DetectionSource property field names (BSON)
const (
	DetectionSourceKind = "kind"
	DetectionSourceName = "name"
	DetectionSourceVersion = "version"
	DetectionSourceRunId = "runId"
	DetectionSourceInputWidth = "inputWidth"
	DetectionSourceInputHeight = "inputHeight"
	DetectionSourceScoreThreshold = "scoreThreshold"
	DetectionSourceNmsIou = "nmsIou"
	DetectionSourceRotationApplied = "rotationApplied"
)

// DominantColor property field names (BSON)
const (
	DominantColorRgbs = "rgbs"
	DominantColorHexs = "hexs"
)

// FaceRedaction property field names (BSON)
const (
	FaceRedactionId = "_id"
	FaceRedactionTracks = "tracks"
	FaceRedactionCaseMediaId = "caseMediaId"
)

// FaceRedactionTrack property field names (BSON)
const (
	FaceRedactionTrackId = "id"
	FaceRedactionTrackClassified = "classified"
	FaceRedactionTrackFrames = "frames"
	FaceRedactionTrackTraject = "traject"
	FaceRedactionTrackColorString = "colorStr"
	FaceRedactionTrackSelected = "selected"
	FaceRedactionTrackDeletedFrames = "deletedFrames"
	FaceRedactionTrackFrameCoordinates = "frameCoordinates"
	FaceRedactionTrackConfidence = "confidence"
	FaceRedactionTrackClassId = "classId"
	FaceRedactionTrackShape = "shape"
)

// Sprite property field names (BSON)
const (
	SpriteSpriteFile = "filename"
	SpriteProvider = "provider"
	SpriteInterval = "interval"
)

// Thumbnail property field names (BSON)
const (
	ThumbnailKey = "key"
	ThumbnailThumbnailFile = "thumbnailFile"
)

// Thumby property field names (BSON)
const (
	ThumbyThumbnailFile = "filename"
	ThumbyProvider = "provider"
	ThumbyBase64 = "base64"
	ThumbyInterval = "interval"
)

// TrackBox property field names (BSON)
const (
	TrackBoxX1 = "x1"
	TrackBoxY1 = "y1"
	TrackBoxX2 = "x2"
	TrackBoxY2 = "y2"
	TrackBoxTrackId = "trackId"
	TrackBoxSmoothed = "smoothed"
	TrackBoxEdited = "edited"
	TrackBoxConfidence = "confidence"
	TrackBoxClassId = "classId"
	TrackBoxLabel = "label"
)
