// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// AnalyticsAlertSummary property field names (BSON)
const (
	AnalyticsAlertSummaryAlertId = "alertId"
	AnalyticsAlertSummaryAlertLabel = "alertLabel"
	AnalyticsAlertSummaryType = "type"
	AnalyticsAlertSummaryTotal = "total"
	AnalyticsAlertSummaryCount = "count"
	AnalyticsAlertSummaryIn = "in"
	AnalyticsAlertSummaryOut = "out"
	AnalyticsAlertSummaryRegionIn = "regionIn"
	AnalyticsAlertSummaryDurationSeconds = "durationSeconds"
	AnalyticsAlertSummaryDurationLabel = "durationLabel"
)

// AnalyticsCharts property field names (BSON)
const (
	AnalyticsChartsRecordingsPerHour = "recordingsPerHour"
	AnalyticsChartsCountsPerHourByDevice = "countsPerHourByDevice"
	AnalyticsChartsCountsPerHourByAlert = "countsPerHourByAlert"
	AnalyticsChartsRegionDurationPerHourAlert = "regionDurationPerHourAlert"
)

// AnalyticsCount property field names (BSON)
const (
	AnalyticsCountId = "_id"
	AnalyticsCountOrganisationId = "organisationId"
	AnalyticsCountProjectId = "projectId"
	AnalyticsCountKey = "key"
	AnalyticsCountTimestamp = "timestamp"
	AnalyticsCountUsername = "username"
	AnalyticsCountUserId = "user_id"
	AnalyticsCountDeviceId = "device_id"
	AnalyticsCountSegmentId = "segment_id"
	AnalyticsCountObjectId = "object_id"
	AnalyticsCountObjectName = "object_name"
	AnalyticsCountCount = "count"
	AnalyticsCountDuration = "duration"
	AnalyticsCountAlertId = "alert_id"
	AnalyticsCountAlertName = "alert_name"
	AnalyticsCountSequenceId = "sequence_id"
	AnalyticsCountType = "type"
)

// AnalyticsDashboard property field names (BSON)
const (
	AnalyticsDashboardSummary = "summary"
	AnalyticsDashboardAlerts = "alerts"
	AnalyticsDashboardLists = "lists"
	AnalyticsDashboardCharts = "charts"
)

// AnalyticsEvent property field names (BSON)
const (
	AnalyticsEventKey = "key"
	AnalyticsEventTimestamp = "timestamp"
	AnalyticsEventDeviceId = "deviceId"
	AnalyticsEventDeviceLabel = "deviceLabel"
	AnalyticsEventAlertId = "alertId"
	AnalyticsEventAlertLabel = "alertLabel"
	AnalyticsEventSequenceId = "sequenceId"
	AnalyticsEventObjectId = "objectId"
	AnalyticsEventObjectLabel = "objectLabel"
	AnalyticsEventType = "type"
	AnalyticsEventCount = "count"
	AnalyticsEventDurationSeconds = "durationSeconds"
	AnalyticsEventDurationLabel = "durationLabel"
)

// AnalyticsFilter property field names (BSON)
const (
	AnalyticsFilterTimeRanges = "timeRanges"
	AnalyticsFilterSites = "sites"
	AnalyticsFilterGroups = "groups"
	AnalyticsFilterDevices = "devices"
)

// AnalyticsHours property field names (BSON)
const (
	AnalyticsHoursTotal = "total"
	AnalyticsHoursInstances = "instances"
)

// AnalyticsLists property field names (BSON)
const (
	AnalyticsListsCountEvents = "countEvents"
	AnalyticsListsRegionEvents = "regionEvents"
)

// AnalyticsSummary property field names (BSON)
const (
	AnalyticsSummaryTotalRecordings = "totalRecordings"
	AnalyticsSummaryTotalCounts = "totalCounts"
	AnalyticsSummaryTotalRegions = "totalRegions"
	AnalyticsSummaryTotalRegionDurationSeconds = "totalRegionDurationSeconds"
	AnalyticsSummaryTotalRegionDurationLabel = "totalRegionDurationLabel"
)

// DirectionalTimeSeriesChart property field names (BSON)
const (
	DirectionalTimeSeriesChartAll = "all"
	DirectionalTimeSeriesChartIn = "in"
	DirectionalTimeSeriesChartOut = "out"
)

// Heatmap property field names (BSON)
const (
	HeatmapId = "_id"
	HeatmapOrganisationId = "organisationId"
	HeatmapProjectId = "projectId"
	HeatmapKey = "key"
	HeatmapTimestamp = "timestamp"
	HeatmapUserId = "user_id"
	HeatmapDeviceId = "device_id"
	HeatmapFrameWidth = "frame_width"
	HeatmapFrameHeight = "frame_height"
	HeatmapCoordinates = "coordinates"
)
