// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Audit property field names (BSON)
const (
	AuditCreatedBy = "createdBy"
	AuditCreatedAt = "createdAt"
	AuditUpdatedBy = "updatedBy"
	AuditUpdatedAt = "updatedAt"
	AuditLastAction = "lastAction"
)
