// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// AuditEvent property field names (BSON)
const (
	AuditEventId             = "_id"
	AuditEventOrganisationId = "organisationId"
	AuditEventActorId        = "actorId"
	AuditEventActorName      = "actorName"
	AuditEventAction         = "action"
	AuditEventTargetType     = "targetType"
	AuditEventTargetId       = "targetId"
	AuditEventChanges        = "changes"
	AuditEventMetadata       = "metadata"
	AuditEventTimestamp      = "timestamp"
)

// AuditFieldChange property field names (BSON)
const (
	AuditFieldChangeField    = "field"
	AuditFieldChangeOldValue = "oldValue"
	AuditFieldChangeNewValue = "newValue"
)
