// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// AuditAuthorizationInfo property field names (BSON)
const (
	AuditAuthorizationInfoPermission = "permission"
	AuditAuthorizationInfoResourceType = "resourceType"
	AuditAuthorizationInfoResourceId = "resourceId"
	AuditAuthorizationInfoScope = "scope"
	AuditAuthorizationInfoGranted = "granted"
	AuditAuthorizationInfoPolicy = "policy"
)

// AuditEvent property field names (BSON)
const (
	AuditEventId = "_id"
	AuditEventSchemaVersion = "schemaVersion"
	AuditEventOrganisationId = "organisationId"
	AuditEventProjectId = "projectId"
	AuditEventActorId = "actorId"
	AuditEventActorName = "actorName"
	AuditEventActorType = "actorType"
	AuditEventAction = "action"
	AuditEventOperation = "operation"
	AuditEventAuthorizationInfo = "authorizationInfo"
	AuditEventCategory = "category"
	AuditEventStatus = "status"
	AuditEventTargetType = "targetType"
	AuditEventTargetId = "targetId"
	AuditEventTargetName = "targetName"
	AuditEventChanges = "changes"
	AuditEventRequest = "request"
	AuditEventMetadata = "metadata"
	AuditEventTimestamp = "timestamp"
)

// AuditEventStatus property field names (BSON)
const (
	AuditEventStatusOutcome = "outcome"
	AuditEventStatusCode = "code"
)

// AuditFieldChange property field names (BSON)
const (
	AuditFieldChangeField = "field"
	AuditFieldChangeOldValue = "oldValue"
	AuditFieldChangeNewValue = "newValue"
)

// AuditRequestInfo property field names (BSON)
const (
	AuditRequestInfoId = "id"
	AuditRequestInfoCorrelationId = "correlationId"
	AuditRequestInfoTraceId = "traceId"
	AuditRequestInfoIP = "ip"
	AuditRequestInfoUserAgent = "userAgent"
	AuditRequestInfoMethod = "method"
	AuditRequestInfoPath = "path"
)
