// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// AuditEvent property field names (BSON)
const (
	AuditEventId = "_id"
	AuditEventOrganisationId = "organisationId"
	AuditEventProjectId = "projectId"
	AuditEventActorId = "actorId"
	AuditEventActorName = "actorName"
	AuditEventActorType = "actorType"
	AuditEventAction = "action"
	AuditEventOperation = "operation"
	AuditEventRequiredPermission = "requiredPermission"
	AuditEventCategory = "category"
	AuditEventOutcome = "outcome"
	AuditEventTargetType = "targetType"
	AuditEventTargetId = "targetId"
	AuditEventTargetName = "targetName"
	AuditEventChanges = "changes"
	AuditEventMetadata = "metadata"
	AuditEventTimestamp = "timestamp"
)

// AuditFieldChange property field names (BSON)
const (
	AuditFieldChangeField = "field"
	AuditFieldChangeOldValue = "oldValue"
	AuditFieldChangeNewValue = "newValue"
)
