// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Audit property field names (BSON)
const (
	AuditCreate = "create"
	AuditUpdate = "update"
)

// AuditCreate property field names (BSON)
const (
	AuditCreateCreatedBy = "createdBy"
	AuditCreateCreatedAt = "createdAt"
)

// AuditUpdate property field names (BSON)
const (
	AuditUpdateUpdatedBy = "updatedBy"
	AuditUpdateUpdatedAt = "updatedAt"
	AuditUpdateAction = "action"
)
