// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// CaseMedia property field names (BSON)
const (
	CaseMediaId = "_id"
	CaseMediaTaskId = "task_id"
	CaseMediaOrganisationId = "organisation_id"
	CaseMediaRole = "role"
	CaseMediaParentId = "parent_id"
	CaseMediaAction = "action"
	CaseMediaEditType = "edit_type"
	CaseMediaVersion = "version"
	CaseMediaSupersedesId = "supersedes_id"
	CaseMediaSelectedVersionId = "selected_version_id"
	CaseMediaParams = "params"
	CaseMediaSourceMediaId = "source_media_id"
	CaseMediaTimestamp = "timestamp"
	CaseMediaEndTimestamp = "end_timestamp"
	CaseMediaCameraId = "camera_id"
	CaseMediaStorageSolution = "storage_solution"
	CaseMediaVideoFile = "video_file"
	CaseMediaVideoProvider = "video_provider"
	CaseMediaThumbnailFile = "thumbnail_file"
	CaseMediaThumbnailProvider = "thumbnail_provider"
	CaseMediaSpriteFile = "sprite_file"
	CaseMediaSpriteProvider = "sprite_provider"
	CaseMediaSpriteInterval = "sprite_interval"
	CaseMediaMedia = "media"
	CaseMediaAnalysis = "analysis"
	CaseMediaFile = "file"
	CaseMediaProvider = "provider"
	CaseMediaStatus = "status"
	CaseMediaStatusError = "status_error"
	CaseMediaAnalysisId = "analysis_id"
	CaseMediaFaceRedactionId = "face_redaction_id"
	CaseMediaCreatedAt = "created_at"
	CaseMediaCreatedBy = "created_by"
	CaseMediaUpdatedAt = "updated_at"
	CaseMediaIncludeInExport = "include_in_export"
	CaseMediaIncludeInShare = "include_in_share"
)
