// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// CaseShare property field names (BSON)
const (
	CaseShareId = "_id"
	CaseShareTaskId = "task_id"
	CaseShareUserId = "user_id"
	CaseShareUserEmail = "user_email"
	CaseShareOrganisationId = "organisation_id"
	CaseShareEmail = "email"
	CaseShareToken = "token"
	CaseSharePermissions = "permissions"
	CaseShareIsActive = "is_active"
	CaseShareExpiresAt = "expires_at"
	CaseShareCreatedAt = "created_at"
	CaseShareOTPCode = "otp_code"
	CaseShareOTPExpiry = "otp_expiry"
	CaseShareOTPAttempts = "otp_attempts"
	CaseShareSelection = "selection"
	CaseShareAttachmentSelection = "attachment_selection"
)
