// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// CaseAttachment property field names (BSON)
const (
	CaseAttachmentId = "_id"
	CaseAttachmentType = "type"
	CaseAttachmentMimeType = "mime_type"
	CaseAttachmentName = "name"
	CaseAttachmentSize = "size"
	CaseAttachmentSha256 = "sha256"
	CaseAttachmentFile = "file"
	CaseAttachmentProvider = "provider"
	CaseAttachmentThumbnailFile = "thumbnail_file"
	CaseAttachmentThumbnailProvider = "thumbnail_provider"
	CaseAttachmentRelatedCaseMediaId = "related_case_media_id"
	CaseAttachmentCreatedAt = "created_at"
	CaseAttachmentCreatedBy = "created_by"
	CaseAttachmentUpdatedAt = "updated_at"
	CaseAttachmentIncludeInExport = "include_in_export"
	CaseAttachmentIncludeInShare = "include_in_share"
)
