// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Alexa property field names (BSON)
const (
	AlexaEnabled = "enabled"
	AlexaValid = "valid"
	AlexaAccesscode = "accesscode"
)

// ChannelTest property field names (BSON)
const (
	ChannelTestEvents = "events"
	ChannelTestData = "data"
)

// ChannelTestData property field names (BSON)
const (
	ChannelTestDataUserId = "userId"
	ChannelTestDataChannel = "channel"
)

// ChannelUpdate property field names (BSON)
const (
	ChannelUpdateChannels = "channels"
)

// ChannelUpdatePayload property field names (BSON)
const (
	ChannelUpdatePayloadChannel = "channel"
	ChannelUpdatePayloadPayload = "payload"
)

// Channels property field names (BSON)
const (
	ChannelsPushbullet = "pushbullet"
	ChannelsEmail = "email"
	ChannelsSlack = "slack"
	ChannelsTelegram = "telegram"
	ChannelsAlexa = "alexa"
	ChannelsWebhook = "webhook"
	ChannelsIfttt = "ifttt"
	ChannelsPushover = "pushover"
	ChannelsSms = "sms"
)

// Email property field names (BSON)
const (
	EmailEnabled = "enabled"
	EmailValid = "valid"
	EmailAddress = "address"
)

// Ifttt property field names (BSON)
const (
	IftttEnabled = "enabled"
	IftttValid = "valid"
	IftttToken = "token"
)

// Pushbullet property field names (BSON)
const (
	PushbulletEnabled = "enabled"
	PushbulletValid = "valid"
	PushbulletApikey = "apikey"
)

// Pushover property field names (BSON)
const (
	PushoverEnabled = "enabled"
	PushoverValid = "valid"
	PushoverApikey = "apikey"
	PushoverSendto = "sendto"
)

// Slack property field names (BSON)
const (
	SlackEnabled = "enabled"
	SlackValid = "valid"
	SlackApikey = "apikey"
	SlackChannel = "channel"
	SlackHook = "hook"
	SlackUsername = "username"
)

// Sms property field names (BSON)
const (
	SmsEnabled = "enabled"
	SmsValid = "valid"
	SmsAccountsid = "accountsid"
	SmsAuthToken = "authtoken"
	SmsFrom = "from"
	SmsTo = "to"
)

// Telegram property field names (BSON)
const (
	TelegramEnabled = "enabled"
	TelegramValid = "valid"
	TelegramToken = "token"
	TelegramChannel = "channel"
)

// Webhook property field names (BSON)
const (
	WebhookEnabled = "enabled"
	WebhookValid = "valid"
	WebhookUrl = "url"
)
