// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// TimeSeries property field names (BSON)
const (
	TimeSeriesKey = "key"
	TimeSeriesLabel = "label"
	TimeSeriesData = "data"
)

// TimeSeriesChart property field names (BSON)
const (
	TimeSeriesChartMetric = "metric"
	TimeSeriesChartGranularity = "granularity"
	TimeSeriesChartTimezone = "timezone"
	TimeSeriesChartSeries = "series"
)

// TimeSeriesDataPoint property field names (BSON)
const (
	TimeSeriesDataPointTime = "time"
	TimeSeriesDataPointValue = "value"
)
