// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Comment property field names (BSON)
const (
	CommentId = "_id"
	CommentDeviceId = "deviceId"
	CommentOrganisationId = "organisationId"
	CommentType = "type"
	CommentAuthor = "author"
	CommentContent = "comment"
	CommentTimestamps = "timestamps"
	CommentParentId = "parentId"
	CommentAudit = "audit"
)
