// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// CameraMetadata property field names (BSON)
const (
	CameraMetadataResolution = "resolution"
	CameraMetadataFieldOfView = "fieldOfView"
	CameraMetadataFrameRate = "frameRate"
	CameraMetadataBitrate = "bitrate"
	CameraMetadataCodec = "codec"
	CameraMetadataHasOnvif = "hasOnvif"
	CameraMetadataHasAudio = "hasAudio"
	CameraMetadataHasZoom = "hasZoom"
	CameraMetadataHasBackChannel = "hasBackChannel"
	CameraMetadataHasPanTilt = "hasPanTilt"
	CameraMetadataHasPresets = "hasPresets"
	CameraMetadataHasIO = "hasIO"
	CameraMetadataPresets = "presets"
	CameraMetadataTours = "tours"
	CameraMetadataIOs = "ios"
)

// CameraPreset property field names (BSON)
const (
	CameraPresetName = "name"
	CameraPresetToken = "token"
	CameraPresetX = "x"
	CameraPresetY = "y"
	CameraPresetZ = "z"
)

// CameraTour property field names (BSON)
const (
	CameraTourName = "name"
	CameraTourPresets = "presets"
	CameraTourCurrent = "current"
	CameraTourRunning = "running"
	CameraTourLoop = "loop"
	CameraTourSpeed = "speed"
)

// Device property field names (BSON)
const (
	DeviceId = "_id"
	DeviceKey = "key"
	DeviceName = "name"
	DeviceType = "type"
	DeviceRepository = "repository"
	DeviceVersion = "version"
	DeviceDeployment = "deployment"
	DeviceOrganisationId = "organisationId"
	DeviceSiteIds = "siteIds"
	DeviceGroupIds = "groupIds"
	DeviceConnectionStart = "connectionStart"
	DeviceDeviceLastSeen = "deviceLastSeen"
	DeviceAgentLastSeen = "agentLastSeen"
	DeviceIdleThreshold = "idleThreshold"
	DeviceDisconnectedThreshold = "disconnectedThreshold"
	DeviceHealthyThreshold = "healthyThreshold"
	DeviceLocation = "location"
	DeviceMetadata = "metadata"
	DeviceCameraMetadata = "cameraMetadata"
	DeviceLightSensorMetadata = "lightSensorMetadata"
	DeviceHumiditySensorMetadata = "humiditySensorMetadata"
	DeviceGPSMetadata = "gpsMetadata"
	DeviceFeaturePermissions = "featurePermissions"
	DeviceAtRuntimeMetadata = "atRuntimeMetadata"
	DeviceAudit = "audit"
)

// DeviceAtRuntimeMetadata property field names (BSON)
const (
	DeviceAtRuntimeMetadataStatus = "status"
)

// DeviceKey property field names (BSON)
const (
	DeviceKeyKey = "key"
	DeviceKeyName = "name"
)

// DeviceMetadata property field names (BSON)
const (
	DeviceMetadataHidden = "hidden"
	DeviceMetadataColor = "color"
	DeviceMetadataBrand = "brand"
	DeviceMetadataModel = "model"
	DeviceMetadataDescription = "description"
	DeviceMetadataLastMaintenance = "lastMaintenance"
	DeviceMetadataInstallationDate = "installationDate"
	DeviceMetadataOnFloorPlans = "onFloorPlans"
	DeviceMetadataIPAddress = "ipAddress"
	DeviceMetadataMacAddress = "macAddress"
	DeviceMetadataBootTime = "bootTime"
	DeviceMetadataArchitecture = "architecture"
	DeviceMetadataHostname = "hostname"
	DeviceMetadataFreeMemory = "freeMemory"
	DeviceMetadataTotalMemory = "totalMemory"
	DeviceMetadataUsedMemory = "usedMemory"
	DeviceMetadataProcessMemory = "processMemory"
	DeviceMetadataEncrypted = "encrypted"
	DeviceMetadataEncryptedData = "encryptedData"
	DeviceMetadataHubEncryption = "hubEncryption"
	DeviceMetadataE2EEncryption = "e2eEncryption"
)

// DeviceOption property field names (BSON)
const (
	DeviceOptionId = "id"
	DeviceOptionValue = "value"
	DeviceOptionText = "text"
)

// GPSMetadata property field names (BSON)
const (
	GPSMetadataLatitude = "latitude"
	GPSMetadataLongitude = "longitude"
	GPSMetadataAltitude = "altitude"
	GPSMetadataAccuracy = "accuracy"
	GPSMetadataTimestamp = "timestamp"
	GPSMetadataSpeed = "speed"
	GPSMetadataHeading = "heading"
)

// HumiditySensorMetadata property field names (BSON)
const (
	HumiditySensorMetadataSensitivity = "sensitivity"
	HumiditySensorMetadataHumidityRange = "humidityRange"
	HumiditySensorMetadataCurrentHumidity = "currentHumidity"
	HumiditySensorMetadataUnit = "unit"
)

// LightSensorMetadata property field names (BSON)
const (
	LightSensorMetadataSensitivity = "sensitivity"
	LightSensorMetadataLuxRange = "luxRange"
	LightSensorMetadataCurrentLux = "currentLux"
	LightSensorMetadataUnit = "unit"
)
