// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// DevicePlacement property field names (BSON)
const (
	DevicePlacementId = "_id"
	DevicePlacementDeviceId = "deviceId"
	DevicePlacementFabricKey = "fabricKey"
	DevicePlacementX = "x"
	DevicePlacementY = "y"
	DevicePlacementRelativeX = "relativeX"
	DevicePlacementRelativeY = "relativeY"
	DevicePlacementRadius = "radius"
	DevicePlacementFieldOfView = "fieldOfView"
	DevicePlacementSliceStartAngle = "sliceStartAngle"
	DevicePlacementSliceEndAngle = "sliceEndAngle"
	DevicePlacementSliceMiddleAngle = "sliceMiddleAngle"
	DevicePlacementColor = "color"
	DevicePlacementIcon = "icon"
	DevicePlacementAudit = "audit"
)

// FloorPlan property field names (BSON)
const (
	FloorPlanId = "_id"
	FloorPlanName = "name"
	FloorPlanImage = "image"
	FloorPlanWidth = "width"
	FloorPlanHeight = "height"
	FloorPlanDevicePlacements = "devicePlacements"
	FloorPlanAudit = "audit"
)
