// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Group property field names (BSON)
const (
	GroupId = "_id"
	GroupName = "name"
	GroupDescription = "description"
	GroupGroupType = "group_type"
	GroupOrganisationId = "organisationId"
	GroupDevices = "devices"
	GroupGroups = "groups"
	GroupSites = "sites"
	GroupStorageSolution = "storageSolution"
	GroupVaultAccessKey = "vaultAccessKey"
	GroupVaultSecretKey = "vaultSecretKey"
	GroupVaultUri = "vaultUri"
	GroupMetadata = "metadata"
	GroupAudit = "audit"
)

// GroupMetadata property field names (BSON)
const (
	GroupMetadataInitials = "initials"
	GroupMetadataColor = "color"
	GroupMetadataFloorPlans = "floorPlans"
	GroupMetadataNumberOfFloorPlans = "numberOfFloorPlans"
	GroupMetadataLocation = "location"
)

// GroupOption property field names (BSON)
const (
	GroupOptionValue = "value"
	GroupOptionText = "text"
	GroupOptionDevices = "devices"
	GroupOptionGroups = "groups"
	GroupOptionSites = "sites"
)
