// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Health property field names (BSON)
const (
	HealthDescription = "description"
	HealthDatabase = "database"
	HealthQueue = "queue"
	HealthLicense = "license"
	HealthMetadata = "metadata"
	HealthAtRuntimeMetadata = "atRuntimeMetadata"
	HealthSynchronize = "synchronize"
	HealthAudit = "audit"
)

// HealthMetadata property field names (BSON)
const (
	HealthMetadataLicenseExpiryDate = "licenseExpiryDate"
)
