// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// HighUpload property field names (BSON)
const (
	HighUploadStartTimestamp = "start_timestamp"
)
