// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// IO property field names (BSON)
const (
	IOId = "_id"
	IOHash = "hash"
	IODeviceId = "deviceId"
	IOType = "type"
	IOKey = "key"
	IOValue = "value"
	IOLastSeenTimestamp = "lastSeenTimestamp"
	IOExternal = "external"
	IOAudit = "audit"
)
