// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Label property field names (BSON)
const (
	LabelId = "_id"
	LabelOrganisationId = "organisationId"
	LabelName = "name"
	LabelDescription = "description"
	LabelColor = "color"
	LabelIsPrivate = "is_private"
	LabelTypes = "type"
	LabelProjectId = "projectId"
	LabelUserId = "user_id"
	LabelOwnerId = "owner_id"
	LabelCreatedAt = "created_at"
	LabelAudit = "audit"
)

// LabelWrapper property field names (BSON)
const (
	LabelWrapperLabel = "label"
)
