// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Location property field names (BSON)
const (
	LocationName = "name"
	LocationLatitude = "latitude"
	LocationLongitude = "longitude"
	LocationAltitude = "altitude"
	LocationAddress = "address"
)
