// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Marker property field names (BSON)
const (
	MarkerId = "_id"
	MarkerDeviceId = "deviceId"
	MarkerSiteId = "siteId"
	MarkerGroupId = "groupId"
	MarkerOrganisationId = "organisationId"
	MarkerStartTimestamp = "startTimestamp"
	MarkerEndTimestamp = "endTimestamp"
	MarkerDuration = "duration"
	MarkerName = "name"
	MarkerEvents = "events"
	MarkerTags = "tags"
	MarkerDescription = "description"
	MarkerCategories = "categories"
	MarkerMetadata = "metadata"
	MarkerAtRuntimeMetadata = "atRuntimeMetadata"
	MarkerSynchronize = "synchronize"
	MarkerAudit = "audit"
)

// MarkerAtRuntimeMetadata property field names (BSON)
const (
	MarkerAtRuntimeMetadataMarkerRanges = "markerRanges"
	MarkerAtRuntimeMetadataTagRanges = "tagRanges"
	MarkerAtRuntimeMetadataEventRanges = "eventRanges"
)

// MarkerCategory property field names (BSON)
const (
	MarkerCategoryName = "name"
)

// MarkerCategoryOption property field names (BSON)
const (
	MarkerCategoryOptionId = "_id"
	MarkerCategoryOptionValue = "value"
	MarkerCategoryOptionText = "text"
	MarkerCategoryOptionOrganisationId = "organisationId"
	MarkerCategoryOptionCreatedAt = "createdAt"
	MarkerCategoryOptionUpdatedAt = "updatedAt"
)

// MarkerEvent property field names (BSON)
const (
	MarkerEventStartTimestamp = "startTimestamp"
	MarkerEventEndTimestamp = "endTimestamp"
	MarkerEventDuration = "duration"
	MarkerEventName = "name"
	MarkerEventDescription = "description"
	MarkerEventTags = "tags"
)

// MarkerEventOption property field names (BSON)
const (
	MarkerEventOptionId = "_id"
	MarkerEventOptionValue = "value"
	MarkerEventOptionText = "text"
	MarkerEventOptionOrganisationId = "organisationId"
	MarkerEventOptionCreatedAt = "createdAt"
	MarkerEventOptionUpdatedAt = "updatedAt"
)

// MarkerEventTimeRange property field names (BSON)
const (
	MarkerEventTimeRangeId = "_id"
	MarkerEventTimeRangeValue = "value"
	MarkerEventTimeRangeText = "text"
	MarkerEventTimeRangeOrganisationId = "organisationId"
	MarkerEventTimeRangeStart = "start"
	MarkerEventTimeRangeEnd = "end"
	MarkerEventTimeRangeDeviceId = "deviceId"
	MarkerEventTimeRangeCreatedAt = "createdAt"
	MarkerEventTimeRangeUpdatedAt = "updatedAt"
)

// MarkerMetadata property field names (BSON)
const (
	MarkerMetadataComments = "comments"
)

// MarkerOption property field names (BSON)
const (
	MarkerOptionId = "_id"
	MarkerOptionOrganisationId = "organisationId"
	MarkerOptionValue = "value"
	MarkerOptionText = "text"
	MarkerOptionCategories = "categories"
	MarkerOptionCreatedAt = "createdAt"
	MarkerOptionUpdatedAt = "updatedAt"
)

// MarkerOptionTimeRange property field names (BSON)
const (
	MarkerOptionTimeRangeId = "_id"
	MarkerOptionTimeRangeValue = "value"
	MarkerOptionTimeRangeText = "text"
	MarkerOptionTimeRangeOrganisationId = "organisationId"
	MarkerOptionTimeRangeStart = "start"
	MarkerOptionTimeRangeEnd = "end"
	MarkerOptionTimeRangeDeviceId = "deviceId"
	MarkerOptionTimeRangeCreatedAt = "createdAt"
	MarkerOptionTimeRangeUpdatedAt = "updatedAt"
)

// MarkerTag property field names (BSON)
const (
	MarkerTagName = "name"
)

// MarkerTagOption property field names (BSON)
const (
	MarkerTagOptionId = "_id"
	MarkerTagOptionValue = "value"
	MarkerTagOptionText = "text"
	MarkerTagOptionOrganisationId = "organisationId"
	MarkerTagOptionCreatedAt = "createdAt"
	MarkerTagOptionUpdatedAt = "updatedAt"
)

// MarkerTagTimeRange property field names (BSON)
const (
	MarkerTagTimeRangeId = "_id"
	MarkerTagTimeRangeValue = "value"
	MarkerTagTimeRangeText = "text"
	MarkerTagTimeRangeOrganisationId = "organisationId"
	MarkerTagTimeRangeStart = "start"
	MarkerTagTimeRangeEnd = "end"
	MarkerTagTimeRangeDeviceId = "deviceId"
	MarkerTagTimeRangeCreatedAt = "createdAt"
	MarkerTagTimeRangeUpdatedAt = "updatedAt"
)
