// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Classification property field names (BSON)
const (
	ClassificationKey = "key"
	ClassificationCentroids = "centroids"
	ClassificationDuration = "duration"
)

// ClassificationSummary property field names (BSON)
const (
	ClassificationSummaryKey = "key"
	ClassificationSummaryCount = "count"
)

// CountingSummary property field names (BSON)
const (
	CountingSummaryKey = "key"
	CountingSummaryCount = "count"
	CountingSummaryDuration = "duration"
)

// HourRange property field names (BSON)
const (
	HourRangeStart = "start"
	HourRangeEnd = "end"
)

// Media property field names (BSON)
const (
	MediaId = "_id"
	MediaStartTimestamp = "startTimestamp"
	MediaEndTimestamp = "endTimestamp"
	MediaDuration = "duration"
	MediaDeviceKey = "deviceKey"
	MediaGroupId = "groupId"
	MediaSiteId = "siteId"
	MediaOrganisationId = "organisationId"
	MediaStorageSolution = "storageSolution"
	MediaVideoFile = "videoFile"
	MediaVideoProvider = "videoProvider"
	MediaThumbnailFile = "thumbnailFile"
	MediaThumbnailProvider = "thumbnailProvider"
	MediaSpriteFile = "spriteFile"
	MediaSpriteProvider = "spriteProvider"
	MediaRedactionFile = "redactionFile"
	MediaRedactionProvider = "redactionProvider"
	MediaClassificationSummary = "classificationSummary"
	MediaCountingSummary = "countingSummary"
	MediaDeviceName = "deviceName"
	MediaMetadata = "metadata"
	MediaAtRuntimeMetadata = "atRuntimeMetadata"
	MediaAudit = "audit"
)

// MediaAtRuntimeMetadata property field names (BSON)
const (
	MediaAtRuntimeMetadataDateTime = "dateTime"
	MediaAtRuntimeMetadataCachedTimestamp = "cachedTimestamp"
	MediaAtRuntimeMetadataVideoUrl = "videoUrl"
	MediaAtRuntimeMetadataThumbnailUrl = "thumbnailUrl"
	MediaAtRuntimeMetadataSpriteUrl = "spriteUrl"
	MediaAtRuntimeMetadataRedactionUrl = "redactionUrl"
	MediaAtRuntimeMetadataAnalysis = "analysis"
	MediaAtRuntimeMetadataDevice = "device"
	MediaAtRuntimeMetadataDurationFormatted = "durationFormatted"
)

// MediaMetadata property field names (BSON)
const (
	MediaMetadataContainer = "containerType"
	MediaMetadataResolution = "resolution"
	MediaMetadataWidth = "width"
	MediaMetadataHeight = "height"
	MediaMetadataCodec = "codec"
	MediaMetadataBitrate = "bitrate"
	MediaMetadataFPS = "fps"
	MediaMetadataFileSize = "fileSize"
	MediaMetadataTags = "tags"
	MediaMetadataThumbnailWidth = "thumbnailWidth"
	MediaMetadataThumbnailHeight = "thumbnailHeight"
	MediaMetadataThumbnailFileSize = "thumbnailFileSize"
	MediaMetadataSpriteInterval = "spriteInterval"
	MediaMetadataSpriteWidth = "spriteWidth"
	MediaMetadataSpriteHeight = "spriteHeight"
	MediaMetadataSpriteCount = "spriteCount"
	MediaMetadataSpriteFileSize = "spriteFileSize"
	MediaMetadataMotionPixels = "motionPixels"
	MediaMetadataMotionPercentage = "motionPercentage"
	MediaMetadataAnalysisId = "analysisId"
	MediaMetadataClassifications = "classifications"
	MediaMetadataDescription = "description"
	MediaMetadataDetections = "detections"
	MediaMetadataDominantColors = "dominantColors"
	MediaMetadataCount = "count"
	MediaMetadataEmbedding = "embedding"
)

// Region property field names (BSON)
const (
	RegionId = "id"
	RegionDevice = "device"
	RegionWidth = "width"
	RegionHeight = "height"
	RegionRegionPoints = "regionPoints"
)

// TimeRange property field names (BSON)
const (
	TimeRangeStart = "start"
	TimeRangeEnd = "end"
)

// VaultMedia property field names (BSON)
const (
	VaultMediaTimestamp = "timestamp"
	VaultMediaFileName = "filename"
	VaultMediaFileSize = "filesize"
	VaultMediaDevice = "device"
	VaultMediaAccount = "account"
	VaultMediaProvider = "provider"
	VaultMediaStatus = "status"
	VaultMediaFinished = "finished"
	VaultMediaTemporary = "temporary"
	VaultMediaForwarded = "forwarded"
	VaultMediaToBeForwarded = "to_be_forwarded"
	VaultMediaUploaded = "uploaded"
	VaultMediaForwarderId = "forwarder_id"
	VaultMediaForwarderType = "forwarder_type"
	VaultMediaForwarderWorker = "forwarder_worker"
	VaultMediaForwardTimestamp = "forward_timestamp"
	VaultMediaEvents = "events"
	VaultMediaMainProvider = "main_provider"
	VaultMediaSecondaryProvider = "secondary_provider"
	VaultMediaMetadata = "metadata"
	VaultMediaUriExpiryTime = "uriExpiryTime"
)

// VaultMediaEvent property field names (BSON)
const (
	VaultMediaEventTimestamp = "timestamp"
	VaultMediaEventTitle = "title"
	VaultMediaEventDescription = "description"
)

// VaultMediaFragmentCollection property field names (BSON)
const (
	VaultMediaFragmentCollectionKey = "key"
	VaultMediaFragmentCollectionFileName = "filename"
	VaultMediaFragmentCollectionCameraId = "camera_id"
	VaultMediaFragmentCollectionTimestamp = "timestamp"
	VaultMediaFragmentCollectionUrl = "url"
	VaultMediaFragmentCollectionStart = "start"
	VaultMediaFragmentCollectionEnd = "end"
	VaultMediaFragmentCollectionDuration = "duration"
	VaultMediaFragmentCollectionBytesRanges = "bytes_ranges"
	VaultMediaFragmentCollectionBytesRangeOnTime = "bytes_range_on_time"
)

// VaultMediaMetadata property field names (BSON)
const (
	VaultMediaMetadataBytesRanges = "bytes_ranges"
	VaultMediaMetadataBytesRangeOnTime = "bytes_range_on_time"
	VaultMediaMetadataIsFragmented = "is_fragmented"
	VaultMediaMetadataDuration = "duration"
	VaultMediaMetadataTimescale = "timescale"
)
