// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Message property field names (BSON)
const (
	MessageType = "type"
	MessageId = "id"
	MessageAlertId = "alert_id"
	MessageAlertName = "alert_name"
	MessageAlertUser = "alert_user"
	MessageAlertMasterUser = "alert_master_user"
	MessageTimestamp = "timestamp"
	MessageNotificationType = "notification_type"
	MessageTitle = "title"
	MessageBody = "body"
	MessageUnread = "unread"
	MessageUser = "user"
	MessageUserId = "userid"
	MessageTimezone = "timezone"
	MessageEmail = "email"
	MessageSequenceId = "sequence_id"
	MessageThumbnail = "thumbnail"
	MessageThumbnailFile = "thumbnailFile"
	MessageThumbnailProvider = "thumbnailProvider"
	MessageSpriteFile = "spriteFile"
	MessageSpriteInterval = "spriteInterval"
	MessageSpriteProvider = "spriteProvider"
	MessageDeviceId = "device_id"
	MessageDeviceName = "device_name"
	MessageClassifications = "classifications"
	MessageSites = "sites"
	MessageGroups = "groups"
	MessageMediaKey = "media_key"
	MessageMediaProvider = "media_provider"
	MessageMediaSource = "media_source"
	MessageMedia = "media"
	MessageNumberOfMedia = "number_of_media"
	MessageDataUsage = "data_usage"
	MessageData = "data"
)
