// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Model property field names (BSON)
const (
	ModelId = "_id"
	ModelMetadata = "metadata"
	ModelAtRuntimeMetadata = "atRuntimeMetadata"
	ModelAudit = "audit"
)

// ModelOption property field names (BSON)
const (
	ModelOptionValue = "value"
	ModelOptionText = "text"
)
