// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// FragmentedBytesRangeOnTime property field names (BSON)
const (
	FragmentedBytesRangeOnTimeDuration = "duration"
	FragmentedBytesRangeOnTimeTime = "time"
	FragmentedBytesRangeOnTimeRange = "range"
)
