// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Detections property field names (BSON)
const (
	DetectionsEnabled = "enabled"
	DetectionsChannelsAll = "channelsAll"
	DetectionsChannelsList = "channelsList"
	DetectionsDevicesAll = "devicesAll"
	DetectionsDevicesList = "devicesList"
	DetectionsClassificationAll = "classificationAll"
	DetectionsClassificationList = "classificationList"
	DetectionsTimeAdvanced = "timeAdvanced"
	DetectionsTimeRange1Max = "timeRange1Max"
	DetectionsTimeRange1Min = "timeRange1Min"
	DetectionsTimeRange2Max = "timeRange2Max"
	DetectionsTimeRange2Min = "timeRange2Min"
)

// Devices property field names (BSON)
const (
	DevicesEnabled = "enabled"
	DevicesChannelsAll = "channelsAll"
	DevicesChannelsList = "channelsList"
	DevicesDevicesAll = "devicesAll"
	DevicesDevicesList = "devicesList"
	DevicesDuration = "duration"
)

// Highupload property field names (BSON)
const (
	HighuploadEnabled = "enabled"
	HighuploadChannelsAll = "channelsAll"
	HighuploadChannelsList = "channelsList"
	HighuploadDevicesAll = "devicesAll"
	HighuploadDevicesList = "devicesList"
	HighuploadRequests = "requests"
)

// NotificationSettings property field names (BSON)
const (
	NotificationSettingsDetections = "detections"
	NotificationSettingsDevices = "devices"
	NotificationSettingsHighupload = "highupload"
)

// NotificationUpdate property field names (BSON)
const (
	NotificationUpdateNotificationSettings = "notificationSettings"
)

// NotificationUpdatePayload property field names (BSON)
const (
	NotificationUpdatePayloadType = "type"
	NotificationUpdatePayloadPayload = "payload"
)

// RegionPoint property field names (BSON)
const (
	RegionPointX = "x"
	RegionPointY = "y"
)
