// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// NotificationEvent property field names (BSON)
const (
	NotificationEventId = "_id"
)

// UserNotificationMailbox property field names (BSON)
const (
	UserNotificationMailboxId = "_id"
	UserNotificationMailboxUserId = "user_id"
	UserNotificationMailboxData = "data"
)
