// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Address property field names (BSON)
const (
	AddressStreetNumber = "street_number"
	AddressStreet = "street"
	AddressStreet2 = "street2"
	AddressCity = "city"
	AddressPostalCode = "postal_code"
	AddressRegion = "region"
	AddressCountry = "country"
	AddressCountryName = "country_name"
)

// CompanyDetails property field names (BSON)
const (
	CompanyDetailsLegalName = "legal_name"
	CompanyDetailsTradingName = "trading_name"
	CompanyDetailsRegistrationNumber = "registration_number"
	CompanyDetailsVATNumber = "vat_number"
	CompanyDetailsTaxId = "tax_id"
	CompanyDetailsIndustry = "industry"
	CompanyDetailsWebsite = "website"
	CompanyDetailsPhone = "phone"
	CompanyDetailsEmail = "email"
	CompanyDetailsLogo = "logo"
)

// Contact property field names (BSON)
const (
	ContactName = "name"
	ContactEmail = "email"
	ContactPhone = "phone"
	ContactRole = "role"
)

// Organisation property field names (BSON)
const (
	OrganisationId = "_id"
	OrganisationName = "name"
	OrganisationDescription = "description"
	OrganisationDomain = "domain"
	OrganisationOwnerId = "owner_id"
	OrganisationSettings = "settings"
	OrganisationIsActive = "is_active"
	OrganisationCompany = "company"
	OrganisationSubscription = "subscription"
	OrganisationBillingAddress = "billing_address"
	OrganisationAudit = "audit"
)

// OrganisationInvitation property field names (BSON)
const (
	OrganisationInvitationId = "_id"
	OrganisationInvitationOrganisationId = "organisation_id"
	OrganisationInvitationEmail = "email"
	OrganisationInvitationRoleIds = "role_ids"
	OrganisationInvitationToken = "token"
	OrganisationInvitationInvitedBy = "invited_by"
	OrganisationInvitationStatus = "status"
	OrganisationInvitationExpiresAt = "expires_at"
	OrganisationInvitationAudit = "audit"
)

// OrganisationMember property field names (BSON)
const (
	OrganisationMemberOrganisationId = "organisation_id"
	OrganisationMemberMembership = "membership"
	OrganisationMemberUser = "user"
	OrganisationMemberRoleAssignments = "role_assignments"
	OrganisationMemberRoles = "roles"
)

// OrganisationSettings property field names (BSON)
const (
	OrganisationSettingsForceMFA = "force_mfa"
	OrganisationSettingsAllowedDomains = "allowed_domains"
	OrganisationSettingsDefaultRoleId = "default_role_id"
	OrganisationSettingsMaxMembers = "max_members"
	OrganisationSettingsAllowInvitations = "allow_invitations"
	OrganisationSettingsFinancialContact = "financial_contact"
	OrganisationSettingsTechnicalContact = "technical_contact"
	OrganisationSettingsPrimaryContact = "primary_contact"
)

// OrganisationUser property field names (BSON)
const (
	OrganisationUserId = "_id"
	OrganisationUserUserId = "user_id"
	OrganisationUserOrganisationId = "organisation_id"
	OrganisationUserStatus = "status"
	OrganisationUserInvitedBy = "invited_by"
	OrganisationUserInvitedAt = "invited_at"
	OrganisationUserJoinedAt = "joined_at"
	OrganisationUserExpiresAt = "expires_at"
	OrganisationUserAudit = "audit"
)

// OrganisationUserDetails property field names (BSON)
const (
	OrganisationUserDetailsUserId = "user_id"
	OrganisationUserDetailsMembership = "membership"
	OrganisationUserDetailsOrganisation = "organisation"
	OrganisationUserDetailsRoleAssignments = "role_assignments"
	OrganisationUserDetailsRoles = "roles"
)
