// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Address property field names (BSON)
const (
	AddressStreetNumber = "streetNumber"
	AddressStreet = "street"
	AddressStreet2 = "street2"
	AddressCity = "city"
	AddressPostalCode = "postalCode"
	AddressRegion = "region"
	AddressCountry = "country"
	AddressCountryName = "countryName"
)

// CompanyDetails property field names (BSON)
const (
	CompanyDetailsLegalName = "legalName"
	CompanyDetailsTradingName = "tradingName"
	CompanyDetailsRegistrationNumber = "registrationNumber"
	CompanyDetailsVATNumber = "vatNumber"
	CompanyDetailsTaxId = "taxId"
	CompanyDetailsIndustry = "industry"
	CompanyDetailsWebsite = "website"
	CompanyDetailsPhone = "phone"
	CompanyDetailsEmail = "email"
	CompanyDetailsLogo = "logo"
)

// Contact property field names (BSON)
const (
	ContactName = "name"
	ContactEmail = "email"
	ContactPhone = "phone"
	ContactRole = "role"
)

// Organisation property field names (BSON)
const (
	OrganisationId = "_id"
	OrganisationName = "name"
	OrganisationDescription = "description"
	OrganisationDomain = "domain"
	OrganisationOwnerId = "ownerId"
	OrganisationSettings = "settings"
	OrganisationIsActive = "isActive"
	OrganisationCompany = "company"
	OrganisationSubscription = "subscription"
	OrganisationBillingAddress = "billingAddress"
	OrganisationAudit = "audit"
)

// OrganisationInvitation property field names (BSON)
const (
	OrganisationInvitationId = "_id"
	OrganisationInvitationOrganisationId = "organisationId"
	OrganisationInvitationEmail = "email"
	OrganisationInvitationRoleIds = "roleIds"
	OrganisationInvitationScope = "scope"
	OrganisationInvitationToken = "token"
	OrganisationInvitationInvitedBy = "invitedBy"
	OrganisationInvitationStatus = "status"
	OrganisationInvitationExpiresAt = "expiresAt"
	OrganisationInvitationAudit = "audit"
)

// OrganisationMember property field names (BSON)
const (
	OrganisationMemberOrganisationId = "organisationId"
	OrganisationMemberMembership = "membership"
	OrganisationMemberUser = "user"
	OrganisationMemberRoleAssignments = "roleAssignments"
	OrganisationMemberRoles = "roles"
)

// OrganisationSettings property field names (BSON)
const (
	OrganisationSettingsForceMFA = "forceMFA"
	OrganisationSettingsAllowedDomains = "allowedDomains"
	OrganisationSettingsDefaultRoleId = "defaultRoleId"
	OrganisationSettingsMaxMembers = "maxMembers"
	OrganisationSettingsAllowInvitations = "allowInvitations"
	OrganisationSettingsFinancialContact = "financialContact"
	OrganisationSettingsTechnicalContact = "technicalContact"
	OrganisationSettingsPrimaryContact = "primaryContact"
)

// OrganisationUser property field names (BSON)
const (
	OrganisationUserId = "_id"
	OrganisationUserUserId = "userId"
	OrganisationUserOrganisationId = "organisationId"
	OrganisationUserStatus = "status"
	OrganisationUserInvitedBy = "invitedBy"
	OrganisationUserInvitedAt = "invitedAt"
	OrganisationUserJoinedAt = "joinedAt"
	OrganisationUserExpiresAt = "expiresAt"
	OrganisationUserAudit = "audit"
)

// OrganisationUserDetails property field names (BSON)
const (
	OrganisationUserDetailsUserId = "userId"
	OrganisationUserDetailsMembership = "membership"
	OrganisationUserDetailsOrganisation = "organisation"
	OrganisationUserDetailsRoleAssignments = "roleAssignments"
	OrganisationUserDetailsRoles = "roles"
)
