// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Permissions property field names (BSON)
const (
	PermissionsPages = "pages"
	PermissionsFeatures = "featurePermissions"
)
