// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// DeviceFeaturePermissions property field names (BSON)
const (
	DeviceFeaturePermissionsPTZ = "ptz"
	DeviceFeaturePermissionsLiveview = "liveview"
	DeviceFeaturePermissionsRemoteConfig = "remoteConfig"
	DeviceFeaturePermissionsIO = "io"
	DeviceFeaturePermissionsFloorPlans = "floorPlans"
)
