// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// PipelinePayload property field names (BSON)
const (
	PipelinePayloadIsFragmented = "is_fragmented"
	PipelinePayloadBytesRanges = "bytes_ranges"
	PipelinePayloadBytesRangeOnTime = "bytes_range_on_time"
)
