// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Plan property field names (BSON)
const (
	PlanLevel = "level"
	PlanUploadLimit = "uploadLimit"
	PlanVideoLimit = "videoLimit"
	PlanUsage = "usage"
	PlanAnalysisLimit = "analysisLimit"
	PlanDayLimit = "dayLimit"
)
