// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Project property field names (BSON)
const (
	ProjectId = "_id"
	ProjectOrganisationId = "organisationId"
	ProjectName = "name"
	ProjectSlug = "slug"
	ProjectDescription = "description"
	ProjectIsActive = "isActive"
	ProjectPublicKey = "publicKey"
	ProjectPrivateKey = "privateKey"
	ProjectEncryptionKey = "encryptionKey"
	ProjectAudit = "audit"
)
