// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// RoleAssignment property field names (BSON)
const (
	RoleAssignmentId = "_id"
	RoleAssignmentUserId = "userId"
	RoleAssignmentRoleId = "roleId"
	RoleAssignmentOrganisationId = "organisationId"
	RoleAssignmentExpiresAt = "expiresAt"
	RoleAssignmentIsActive = "isActive"
	RoleAssignmentScope = "scope"
	RoleAssignmentAudit = "audit"
)

// RoleAssignmentScope property field names (BSON)
const (
	RoleAssignmentScopeSiteIds = "siteIds"
	RoleAssignmentScopeGroupIds = "groupIds"
	RoleAssignmentScopeDeviceIds = "deviceIds"
)

// UserRoleAssignments property field names (BSON)
const (
	UserRoleAssignmentsUserId = "userId"
	UserRoleAssignmentsAssignments = "assignments"
	UserRoleAssignmentsRoles = "roles"
)
