// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// FeaturePermissions property field names (BSON)
const (
	FeaturePermissionsPTZ = "ptz"
	FeaturePermissionsLiveview = "liveview"
	FeaturePermissionsRemoteConfig = "remote_config"
	FeaturePermissionsIO = "io"
	FeaturePermissionsFloorPlans = "floorPlans"
)

// Role property field names (BSON)
const (
	RoleId = "_id"
	RoleName = "roleName"
	RoleParentRole = "role"
	RolePages = "pages"
	RoleTimeWindow = "timeWindow"
	RoleUserId = "user_id"
	RoleIsActive = "isActive"
	RoleFeaturePermissions = "featurePermissions"
	RoleTimeWindowActive = "timeWindowActive"
)

// TimeWindow property field names (BSON)
const (
	TimeWindowTimeRange1MinMonday = "timeRange1MinMonday"
	TimeWindowTimeRange1MaxMonday = "timeRange1MaxMonday"
	TimeWindowTimeRange2MinMonday = "timeRange2MinMonday"
	TimeWindowTimeRange2MaxMonday = "timeRange2MaxMonday"
	TimeWindowTimeRange1MinTuesday = "timeRange1MinTuesday"
	TimeWindowTimeRange1MaxTuesday = "timeRange1MaxTuesday"
	TimeWindowTimeRange2MinTuesday = "timeRange2MinTuesday"
	TimeWindowTimeRange2MaxTuesday = "timeRange2MaxTuesday"
	TimeWindowTimeRange1MinWednesday = "timeRange1MinWednesday"
	TimeWindowTimeRange1MaxWednesday = "timeRange1MaxWednesday"
	TimeWindowTimeRange2MinWednesday = "timeRange2MinWednesday"
	TimeWindowTimeRange2MaxWednesday = "timeRange2MaxWednesday"
	TimeWindowTimeRange1MinThursday = "timeRange1MinThursday"
	TimeWindowTimeRange1MaxThursday = "timeRange1MaxThursday"
	TimeWindowTimeRange2MinThursday = "timeRange2MinThursday"
	TimeWindowTimeRange2MaxThursday = "timeRange2MaxThursday"
	TimeWindowTimeRange1MinFriday = "timeRange1MinFriday"
	TimeWindowTimeRange1MaxFriday = "timeRange1MaxFriday"
	TimeWindowTimeRange2MinFriday = "timeRange2MinFriday"
	TimeWindowTimeRange2MaxFriday = "timeRange2MaxFriday"
	TimeWindowTimeRange1MinSaturday = "timeRange1MinSaturday"
	TimeWindowTimeRange1MaxSaturday = "timeRange1MaxSaturday"
	TimeWindowTimeRange2MinSaturday = "timeRange2MinSaturday"
	TimeWindowTimeRange2MaxSaturday = "timeRange2MaxSaturday"
	TimeWindowTimeRange1MinSunday = "timeRange1MinSunday"
	TimeWindowTimeRange1MaxSunday = "timeRange1MaxSunday"
	TimeWindowTimeRange2MinSunday = "timeRange2MinSunday"
	TimeWindowTimeRange2MaxSunday = "timeRange2MaxSunday"
)
