// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// RoleAssignment property field names (BSON)
const (
	RoleAssignmentId = "_id"
	RoleAssignmentUserId = "user_id"
	RoleAssignmentRoleId = "role_id"
	RoleAssignmentOrganisationId = "organisation_id"
	RoleAssignmentExpiresAt = "expires_at"
	RoleAssignmentIsActive = "is_active"
	RoleAssignmentScope = "scope"
	RoleAssignmentAudit = "audit"
)

// RoleAssignmentScope property field names (BSON)
const (
	RoleAssignmentScopeAllOrganisation = "all_organisation"
	RoleAssignmentScopeSiteIds = "site_ids"
	RoleAssignmentScopeGroupIds = "group_ids"
	RoleAssignmentScopeDeviceIds = "device_ids"
)

// UserRoleAssignments property field names (BSON)
const (
	UserRoleAssignmentsUserId = "user_id"
	UserRoleAssignmentsAssignments = "assignments"
	UserRoleAssignmentsRoles = "roles"
)
