// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// RuntimeConfig property field names (BSON)
const (
	RuntimeConfigMqttUsername = "mqttUsername"
	RuntimeConfigMqttPassword = "mqttPassword"
	RuntimeConfigTurnUsername = "turnUsername"
	RuntimeConfigTurnPassword = "turnPassword"
)
