// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Sequence property field names (BSON)
const (
	SequenceId = "_id"
	SequenceOrganisationId = "organisationId"
	SequenceUserId = "user_id"
	SequenceAnalysis = "analysis"
)
