// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Site property field names (BSON)
const (
	SiteId = "_id"
	SiteName = "name"
	SiteDescription = "description"
	SiteOrganisationId = "organisationId"
	SiteDevices = "devices"
	SiteGroups = "groups"
	SiteStorageSolution = "storageSolution"
	SiteVaultAccessKey = "vaultAccessKey"
	SiteVaultSecretKey = "vaultSecretKey"
	SiteVaultUri = "vaultUri"
	SiteMetadata = "metadata"
	SiteAudit = "audit"
	SiteUserId = "user_id"
	SiteInitials = "initials"
	SiteColor = "color"
	SiteAddress = "address"
	SiteAllDevices = "all_devices"
	SiteAccessKey = "access_key"
	SiteSecretKey = "secret_key"
	SiteStorageUri = "storage_uri"
)

// SiteMetadata property field names (BSON)
const (
	SiteMetadataInitials = "initials"
	SiteMetadataColor = "color"
	SiteMetadataFloorPlans = "floorPlans"
	SiteMetadataNumberOfFloorPlans = "numberOfFloorPlans"
	SiteMetadataLocation = "location"
)

// SiteOption property field names (BSON)
const (
	SiteOptionValue = "value"
	SiteOptionText = "text"
	SiteOptionDevices = "devices"
	SiteOptionGroups = "groups"
	SiteOptionMetadata = "metadata"
)
