// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// State property field names (BSON)
const (
	StateId = "_id"
	StateName = "name"
	StateDescription = "description"
	StateDeviceId = "deviceId"
	StateSiteId = "siteId"
	StateGroupId = "groupId"
	StateOrganisationId = "organisationId"
	StateDevices = "devices"
	StateDesiredState = "desiredState"
	StateDesiredStateStartTimestamp = "desiredStateStartTimestamp"
	StateDesiredStateEndTimestamp = "desiredStateEndTimestamp"
	StateTimeSchedule = "timeSchedule"
	StateMetadata = "metadata"
	StateAtRuntimeMetadata = "atRuntimeMetadata"
	StateAudit = "audit"
)

// TimeSchedule property field names (BSON)
const (
	TimeScheduleEnabled = "enabled"
	TimeScheduleCron = "cron"
	TimeScheduleDuration = "duration"
	TimeScheduleTimezone = "timezone"
	TimeScheduleStartDate = "startDate"
	TimeScheduleEndDate = "endDate"
	TimeScheduleDaysOfWeek = "daysOfWeek"
	TimeScheduleStartTime = "startTime"
	TimeScheduleEndTime = "endTime"
)
