// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Subscription property field names (BSON)
const (
	SubscriptionId = "_id"
	SubscriptionOrganisationId = "organisation_id"
	SubscriptionUserId = "user_id"
	SubscriptionStripeId = "stripe_id"
	SubscriptionStripePlan = "stripe_plan"
	SubscriptionQuantity = "quantity"
	SubscriptionStatus = "status"
	SubscriptionTrialEndsAt = "trial_ends_at"
	SubscriptionEndsAt = "ends_at"
	SubscriptionUpdatedAt = "updated_at"
	SubscriptionCreatedAt = "created_at"
)
