// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Subscription property field names (BSON)
const (
	SubscriptionId = "_id"
	SubscriptionUserId = "user_id"
	SubscriptionStripePlan = "stripe_plan"
	SubscriptionEndsAt = "ends_at"
)
