// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Synchronize property field names (BSON)
const (
	SynchronizeTimestamp = "timestamp"
	SynchronizeStatus = "status"
	SynchronizeWorkerId = "workerId"
	SynchronizeMessage = "message"
	SynchronizeEvents = "events"
)

// SynchronizeEvent property field names (BSON)
const (
	SynchronizeEventTimestamp = "timestamp"
	SynchronizeEventStatus = "status"
	SynchronizeEventWorkerId = "workerId"
	SynchronizeEventMessage = "message"
)
