// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// ExportFile property field names (BSON)
const (
	ExportFileTimestamp         = "timestamp"
	ExportFileKey               = "key"
	ExportFileCameraId          = "camera_id"
	ExportFileProvider          = "provider"
	ExportFileSource            = "source"
	ExportFileVideoUrl          = "video_url"
	ExportFileSpriteFile        = "spriteFile"
	ExportFileSpriteProvider    = "spriteProvider"
	ExportFileSpriteUrl         = "sprite_url"
	ExportFileSpriteInterval    = "spriteInterval"
	ExportFileThumbnailFile     = "thumbnailFile"
	ExportFileThumbnailProvider = "thumbnailProvider"
	ExportFileThumbnailUrl      = "thumbnail_url"
)

// MediaWrapper property field names (BSON)
const (
	MediaWrapperTime         = "time"
	MediaWrapperTimestamp    = "timestamp"
	MediaWrapperDescription  = "description"
	MediaWrapperIndex        = "index"
	MediaWrapperInstanceName = "instanceName"
	MediaWrapperLabels       = "labels"
	MediaWrapperProperties   = "properties"
	MediaWrapperMetaData     = "metadata"
	MediaWrapperFileUrl      = "src"
	MediaWrapperThumbnailUrl = "thumbnailUrl"
	MediaWrapperSpriteUrl    = "spriteUrl"
	MediaWrapperType         = "type"
	MediaWrapperVault        = "vault"
	MediaWrapperTaskCreated  = "task_created"
	MediaWrapperPersisted    = "persisted"
)

// Task property field names (BSON)
const (
	TaskId                        = "_id"
	TaskCreationDate              = "creation_date"
	TaskCreationDateTime          = "creation_datetime"
	TaskDate                      = "date"
	TaskMediaTimestamp            = "media_timestamp"
	TaskMediaDate                 = "media_date"
	TaskMediaDateTime             = "media_datetime"
	TaskMediaEndTimestamp         = "media_end_timestamp"
	TaskMediaEndDateTime          = "media_end_datetime"
	TaskUserId                    = "user_id"
	TaskUsername                  = "username"
	TaskReporterId                = "reporter_id"
	TaskTitle                     = "title"
	TaskNotes                     = "notes"
	TaskNotesShort                = "notes_short"
	TaskStatus                    = "status"
	TaskSequenceId                = "sequenceId"
	TaskIsPrivate                 = "is_private"
	TaskCamera                    = "camera"
	TaskCameras                   = "cameras"
	TaskCameraNames               = "camera_names"
	TaskAssignees                 = "assignees"
	TaskReporterProfile           = "reporter_profile"
	TaskReporterEmail             = "reporter_email"
	TaskAssigneesProfile          = "assignees_profile"
	TaskNotifyAssignees           = "notify_assignees"
	TaskAssigneesSentTo           = "assignees_sent_to"
	TaskVideoUrl                  = "video_url"
	TaskVideoFile                 = "videoFile"
	TaskVideoProvider             = "videoProvider"
	TaskThumbnailUrl              = "thumbnail_url"
	TaskThumbnail                 = "thumbnail"
	TaskThumbnailFile             = "thumbnailFile"
	TaskThumbnailProvider         = "thumbnailProvider"
	TaskSpriteUrl                 = "sprite_url"
	TaskSpriteFile                = "spriteFile"
	TaskSpriteProvider            = "spriteProvider"
	TaskSpriteInterval            = "spriteInterval"
	TaskCompressedUrl             = "compressed_url"
	TaskCompressedFile            = "compressedFile"
	TaskCompressedProvider        = "compressedProvider"
	TaskExportStatus              = "export_status"
	TaskExportProgress            = "export_progress"
	TaskExportFiles               = "export_files"
	TaskExportFilesCount          = "export_files_count"
	TaskDownloadedFiles           = "downloaded_files"
	TaskExportRequested           = "export_requested"
	TaskExportInProgress          = "export_in_progress"
	TaskExportRevision            = "export_revision"
	TaskMediaCount                = "media_count"
	TaskExportSelection           = "export_selection"
	TaskShareSelection            = "share_selection"
	TaskExportAttachmentSelection = "export_attachment_selection"
	TaskShareAttachmentSelection  = "share_attachment_selection"
	TaskAttachments               = "attachments"
	TaskRetentionDays             = "retention_days"
	TaskExpiresAt                 = "expires_at"
	TaskExpiresAtOverridden       = "expires_at_overridden"
	TaskLegalHold                 = "legal_hold"
	TaskComments                  = "comments"
	TaskLabels                    = "labels"
)

// TaskStatistics property field names (BSON)
const (
	TaskStatisticsOpen     = "open"
	TaskStatisticsRejected = "rejected"
	TaskStatisticsApproved = "approved"
	TaskStatisticsTotal    = "total"
)

// TaskWrapper property field names (BSON)
const (
	TaskWrapperTask = "task"
)
