// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// ExportFile property field names (BSON)
const (
	ExportFileTimestamp = "timestamp"
	ExportFileKey = "key"
	ExportFileCameraId = "camera_id"
	ExportFileProvider = "provider"
	ExportFileSource = "source"
	ExportFileSpriteFile = "spriteFile"
	ExportFileSpriteProvider = "spriteProvider"
	ExportFileSpriteInterval = "spriteInterval"
	ExportFileThumbnailFile = "thumbnailFile"
	ExportFileThumbnailProvider = "thumbnailProvider"
)

// MediaWrapper property field names (BSON)
const (
	MediaWrapperTime = "time"
	MediaWrapperTimestamp = "timestamp"
	MediaWrapperDescription = "description"
	MediaWrapperIndex = "index"
	MediaWrapperInstanceName = "instanceName"
	MediaWrapperLabels = "labels"
	MediaWrapperProperties = "properties"
	MediaWrapperMetaData = "metadata"
	MediaWrapperFileUrl = "src"
	MediaWrapperThumbnailUrl = "thumbnailUrl"
	MediaWrapperSpriteUrl = "spriteUrl"
	MediaWrapperType = "type"
	MediaWrapperVault = "vault"
	MediaWrapperTaskCreated = "task_created"
	MediaWrapperPersisted = "persisted"
)

// Task property field names (BSON)
const (
	TaskId = "_id"
	TaskCreationDate = "creation_date"
	TaskCreationDateTime = "creation_datetime"
	TaskDate = "date"
	TaskMediaTimestamp = "media_timestamp"
	TaskMediaDate = "media_date"
	TaskMediaDateTime = "media_datetime"
	TaskMediaEndTimestamp = "media_end_timestamp"
	TaskMediaEndDateTime = "media_end_datetime"
	TaskUserId = "user_id"
	TaskUsername = "username"
	TaskReporterId = "reporter_id"
	TaskTitle = "title"
	TaskNotes = "notes"
	TaskNotesShort = "notes_short"
	TaskStatus = "status"
	TaskSequenceId = "sequenceId"
	TaskIsPrivate = "is_private"
	TaskCamera = "camera"
	TaskCameras = "cameras"
	TaskCameraNames = "camera_names"
	TaskAssignees = "assignees"
	TaskReporterProfile = "reporter_profile"
	TaskReporterEmail = "reporter_email"
	TaskAssigneesProfile = "assignees_profile"
	TaskNotifyAssignees = "notify_assignees"
	TaskAssigneesSentTo = "assignees_sent_to"
	TaskVideoUrl = "video_url"
	TaskVideoFile = "videoFile"
	TaskVideoProvider = "videoProvider"
	TaskThumbnailUrl = "thumbnail_url"
	TaskThumbnail = "thumbnail"
	TaskThumbnailFile = "thumbnailFile"
	TaskThumbnailProvider = "thumbnailProvider"
	TaskSpriteUrl = "sprite_url"
	TaskSpriteFile = "spriteFile"
	TaskSpriteProvider = "spriteProvider"
	TaskSpriteInterval = "spriteInterval"
	TaskCompressedUrl = "compressed_url"
	TaskCompressedFile = "compressedFile"
	TaskCompressedProvider = "compressedProvider"
	TaskExportStatus = "export_status"
	TaskExportProgress = "export_progress"
	TaskExportFiles = "export_files"
	TaskExportFilesCount = "export_files_count"
	TaskDownloadedFiles = "downloaded_files"
	TaskComments = "comments"
	TaskLabels = "labels"
)

// TaskFilter property field names (BSON)
const (
	TaskFilterTitle = "title"
	TaskFilterLimit = "limit"
	TaskFilterSites = "sites"
	TaskFilterDevices = "devices"
	TaskFilterGroups = "groups"
	TaskFilterAssignees = "assignees"
	TaskFilterLabels = "labels"
	TaskFilterStatus = "status"
	TaskFilterOffset = "offset"
)

// TaskWrapper property field names (BSON)
const (
	TaskWrapperTask = "task"
)
