// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// MarkerGroup property field names (BSON)
const (
	MarkerGroupStartTimestamp = "startTimestamp"
	MarkerGroupEndTimestamp = "endTimestamp"
	MarkerGroupCount = "count"
	MarkerGroupMarkers = "markers"
)

// MarkerTimeline property field names (BSON)
const (
	MarkerTimelineDevice = "device"
	MarkerTimelineMarkers = "markers"
)

// MediaGroup property field names (BSON)
const (
	MediaGroupStartTimestamp = "startTimestamp"
	MediaGroupEndTimestamp = "endTimestamp"
	MediaGroupCount = "count"
	MediaGroupMedia = "media"
)

// MediaTimeline property field names (BSON)
const (
	MediaTimelineDevice = "device"
	MediaTimelineMedia = "media"
)

// Timeline property field names (BSON)
const (
	TimelineDevice = "device"
	TimelineMedia = "media"
	TimelineMarkers = "markers"
)
