// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Storage property field names (BSON)
const (
	StorageUri = "uri"
	StorageAccessKey = "access_key"
	StorageSecret = "secret_key"
)
