// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Videowall property field names (BSON)
const (
	VideowallId = "_id"
	VideowallName = "name"
	VideowallDescription = "description"
	VideowallSites = "sites"
	VideowallGroups = "groups"
	VideowallCameras = "cameras"
	VideowallIsActive = "isActive"
	VideowallUserId = "user_id"
	VideowallMasterUserId = "master_user_id"
	VideowallPassCode = "pass_code"
	VideowallFingerprint = "fingerprint"
	VideowallShortLink = "short_link"
	VideowallHeader = "header"
	VideowallExpiration = "expiration"
	VideowallPTZ = "ptz"
	VideowallLiveview = "liveview"
	VideowallIO = "io"
	VideowallAssignedUsers = "assigned_users"
)
