// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Videowall property field names (BSON)
const (
	VideowallId = "_id"
	VideowallOrganisationId = "organisationId"
	VideowallName = "name"
	VideowallDescription = "description"
	VideowallSites = "sites"
	VideowallGroups = "groups"
	VideowallCameras = "cameras"
	VideowallIsActive = "isActive"
	VideowallUserId = "user_id"
	VideowallUsername = "username"
	VideowallMasterUserId = "master_user_id"
	VideowallPassCode = "pass_code"
	VideowallFingerprint = "fingerprint"
	VideowallShortLink = "short_link"
	VideowallHeader = "header"
	VideowallExpiration = "expiration"
	VideowallPTZ = "ptz"
	VideowallLiveview = "liveview"
	VideowallIO = "io"
	VideowallAssignedUsers = "assigned_users"
	VideowallWeeklySchedule = "weeklySchedule"
	VideowallDefaultViewingMode = "default_viewing_mode"
	VideowallLayout = "layout"
	VideowallAllowLayoutEdits = "allow_layout_edits"
)

// VideowallLayout property field names (BSON)
const (
	VideowallLayoutColumns = "columns"
	VideowallLayoutTiles = "tiles"
)

// VideowallLayoutTile property field names (BSON)
const (
	VideowallLayoutTileCameraKey = "cameraKey"
	VideowallLayoutTileColSpan = "colSpan"
	VideowallLayoutTileRowSpan = "rowSpan"
)
