// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// DeviceVLMMetadata property field names (BSON)
const (
	DeviceVLMMetadataSchemaVersion = "schemaVersion"
	DeviceVLMMetadataStableStates = "stableStates"
)

// VLMContext property field names (BSON)
const (
	VLMContextMedia = "media"
	VLMContextStableStates = "stableStates"
)

// VLMMediaMetadata property field names (BSON)
const (
	VLMMediaMetadataSchemaVersion = "schemaVersion"
	VLMMediaMetadataScene = "scene"
	VLMMediaMetadataObservations = "observations"
)

// VLMObservation property field names (BSON)
const (
	VLMObservationMarker = "marker"
	VLMObservationEvent = "event"
	VLMObservationTags = "tags"
)

// VLMScene property field names (BSON)
const (
	VLMSceneSummary = "summary"
	VLMSceneStaticElements = "staticElements"
	VLMSceneZones = "zones"
	VLMSceneLighting = "lighting"
)

// VLMStableState property field names (BSON)
const (
	VLMStableStateId = "id"
	VLMStableStateName = "name"
	VLMStableStateScene = "scene"
	VLMStableStateSourceMediaId = "sourceMediaId"
	VLMStableStateSourceMediaKey = "sourceMediaKey"
	VLMStableStateUpdatedAt = "updatedAt"
)
