// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowRunConditionDecision property field names (BSON)
const (
	WorkflowRunConditionDecisionIndex = "index"
	WorkflowRunConditionDecisionOutcome = "outcome"
)

// WorkflowRunStageDecision property field names (BSON)
const (
	WorkflowRunStageDecisionEvaluatedAtMs = "evaluatedatms"
	WorkflowRunStageDecisionEligible = "eligible"
	WorkflowRunStageDecisionNeeds = "needs"
)

// WorkflowRunStageNeedDecision property field names (BSON)
const (
	WorkflowRunStageNeedDecisionIndex = "index"
	WorkflowRunStageNeedDecisionReady = "ready"
	WorkflowRunStageNeedDecisionOutcome = "outcome"
	WorkflowRunStageNeedDecisionConditions = "conditions"
)
