// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Workflow property field names (BSON)
const (
	WorkflowId = "_id"
	WorkflowName = "name"
	WorkflowDescription = "description"
	WorkflowEnabled = "enabled"
	WorkflowSource = "source"
	WorkflowTriggers = "triggers"
	WorkflowTrigger = "trigger"
	WorkflowNodes = "nodes"
	WorkflowEdges = "edges"
	WorkflowStages = "stages"
	WorkflowUserId = "userId"
	WorkflowUsername = "username"
	WorkflowOrganisationId = "organisationId"
	WorkflowProjectId = "projectId"
	WorkflowCreatedAt = "createdAt"
	WorkflowUpdatedAt = "updatedAt"
	WorkflowAudit = "audit"
)

// WorkflowEdge property field names (BSON)
const (
	WorkflowEdgeId = "id"
	WorkflowEdgeSource = "source"
	WorkflowEdgeSourcePort = "sourcePort"
	WorkflowEdgeTarget = "target"
	WorkflowEdgeTargetPort = "targetPort"
	WorkflowEdgeCondition = "condition"
)

// WorkflowNode property field names (BSON)
const (
	WorkflowNodeId = "id"
	WorkflowNodeLabel = "label"
	WorkflowNodeX = "x"
	WorkflowNodeY = "y"
	WorkflowNodeStageRef = "stageRef"
	WorkflowNodeData = "data"
)

// WorkflowTrigger property field names (BSON)
const (
	WorkflowTriggerType = "type"
	WorkflowTriggerDevices = "devices"
	WorkflowTriggerConditions = "conditions"
	WorkflowTriggerWeeklySchedule = "weeklySchedule"
	WorkflowTriggerSurfaces = "surfaces"
)
