// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowRun property field names (BSON)
const (
	WorkflowRunId = "_id"
	WorkflowRunWorkflowId = "workflowid"
	WorkflowRunWorkflowName = "workflowname"
	WorkflowRunStages = "stages"
	WorkflowRunOrigin = "origin"
	WorkflowRunSourceRef = "sourceref"
	WorkflowRunKey = "key"
	WorkflowRunRecordingTimestamp = "recordingtimestamp"
	WorkflowRunOrganisationId = "organisationId"
	WorkflowRunTraceId = "traceid"
	WorkflowRunStart = "start"
	WorkflowRunEnd = "end"
	WorkflowRunInputs = "inputs"
	WorkflowRunResults = "results"
	WorkflowRunDispatchedOperations = "dispatchedoperations"
	WorkflowRunResolvedOperations = "resolvedoperations"
)
