// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// StageCondition property field names (BSON)
const (
	StageConditionPath = "path"
	StageConditionOp = "op"
	StageConditionValue = "value"
)

// StageDependency property field names (BSON)
const (
	StageDependencyOperation = "operation"
	StageDependencyCondition = "condition"
)

// StageResourceList property field names (BSON)
const (
	StageResourceListCPU = "cpu"
	StageResourceListMemory = "memory"
)

// StageResources property field names (BSON)
const (
	StageResourcesRequests = "requests"
	StageResourcesLimits = "limits"
)

// WorkflowStage property field names (BSON)
const (
	WorkflowStageId = "_id"
	WorkflowStageName = "name"
	WorkflowStageDescription = "description"
	WorkflowStageOperation = "operation"
	WorkflowStageDispatch = "dispatch"
	WorkflowStageNeeds = "needs"
	WorkflowStageRepository = "repository"
	WorkflowStageTag = "tag"
	WorkflowStagePullPolicy = "pullPolicy"
	WorkflowStageReplicas = "replicas"
	WorkflowStageQueue = "queue"
	WorkflowStageLogLevel = "logLevel"
	WorkflowStageResources = "resources"
	WorkflowStageEnv = "env"
)
