// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowRunStageDecision property field names (BSON)
const (
	WorkflowRunStageDecisionEvaluatedAtMs = "evaluatedatms"
	WorkflowRunStageDecisionEligible = "eligible"
	WorkflowRunStageDecisionNeeds = "needs"
)

// WorkflowRunStageNeedDecision property field names (BSON)
const (
	WorkflowRunStageNeedDecisionIndex = "index"
	WorkflowRunStageNeedDecisionOutcome = "outcome"
)
