// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// StageCondition property field names (BSON)
const (
	StageConditionPath = "path"
	StageConditionOp = "op"
	StageConditionValue = "value"
)

// StageDependency property field names (BSON)
const (
	StageDependencyOperation = "operation"
	StageDependencyCondition = "condition"
)

// StageParam property field names (BSON)
const (
	StageParamName = "name"
	StageParamLabel = "label"
	StageParamType = "type"
	StageParamRequired = "required"
	StageParamDefault = "default"
	StageParamOptions = "options"
)

// StagePort property field names (BSON)
const (
	StagePortName = "name"
	StagePortLabel = "label"
)

// StageResourceList property field names (BSON)
const (
	StageResourceListCPU = "cpu"
	StageResourceListMemory = "memory"
)

// StageResources property field names (BSON)
const (
	StageResourcesRequests = "requests"
	StageResourcesLimits = "limits"
)

// WorkflowStage property field names (BSON)
const (
	WorkflowStageId = "_id"
	WorkflowStageName = "name"
	WorkflowStageDescription = "description"
	WorkflowStageOperation = "operation"
	WorkflowStageDispatch = "dispatch"
	WorkflowStageNeeds = "needs"
	WorkflowStageNeedsMode = "needsMode"
	WorkflowStageParams = "params"
	WorkflowStageInputs = "inputs"
	WorkflowStageOutputs = "outputs"
	WorkflowStageRepository = "repository"
	WorkflowStageTag = "tag"
	WorkflowStagePullPolicy = "pullPolicy"
	WorkflowStageReplicas = "replicas"
	WorkflowStageQueue = "queue"
	WorkflowStageLogLevel = "logLevel"
	WorkflowStageResources = "resources"
	WorkflowStageEnv = "env"
)
