// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowRunStage property field names (BSON)
const (
	WorkflowRunStageOperation = "operation"
	WorkflowRunStageName = "name"
	WorkflowRunStageQueue = "queue"
	WorkflowRunStageDispatch = "dispatch"
	WorkflowRunStageNeeds = "needs"
	WorkflowRunStageNeedsMode = "needsMode"
	WorkflowRunStageExecution = "execution"
)

// WorkflowRunStageExecutionDetails property field names (BSON)
const (
	WorkflowRunStageExecutionDetailsDispatchAttempts = "dispatchattempts"
	WorkflowRunStageExecutionDetailsFirstDispatchAttemptAtMs = "firstdispatchattemptatms"
	WorkflowRunStageExecutionDetailsLastDispatchAttemptAtMs = "lastdispatchattemptatms"
	WorkflowRunStageExecutionDetailsDispatchedAtMs = "dispatchedatms"
	WorkflowRunStageExecutionDetailsResolvedAtMs = "resolvedatms"
	WorkflowRunStageExecutionDetailsLastDispatchErrorCode = "lastdispatcherrorcode"
	WorkflowRunStageExecutionDetailsDecision = "decision"
)
