// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowConditionSet property field names (BSON)
const (
	WorkflowConditionSetConditionMode = "conditionMode"
	WorkflowConditionSetConditions = "conditions"
)

// WorkflowPredicate property field names (BSON)
const (
	WorkflowPredicatePath = "path"
	WorkflowPredicateOp = "op"
	WorkflowPredicateValue = "value"
)

// WorkflowPredicateSet property field names (BSON)
const (
	WorkflowPredicateSetConditionMode = "conditionMode"
	WorkflowPredicateSetConditions = "conditions"
)
