// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowRunTriggerMatch property field names (BSON)
const (
	WorkflowRunTriggerMatchIndex = "index"
	WorkflowRunTriggerMatchEvaluatedAtMs = "evaluatedatms"
	WorkflowRunTriggerMatchTrigger = "trigger"
	WorkflowRunTriggerMatchMatchedEdgeIds = "matchededgeids"
)
