// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Workflow property field names (BSON)
const (
	WorkflowId = "_id"
	WorkflowName = "name"
	WorkflowDescription = "description"
	WorkflowEnabled = "enabled"
	WorkflowTrigger = "trigger"
	WorkflowNodes = "nodes"
	WorkflowEdges = "edges"
	WorkflowUserId = "user_id"
	WorkflowUsername = "username"
	WorkflowMasterUserId = "master_user_id"
	WorkflowCreatedAt = "created_at"
	WorkflowUpdatedAt = "updated_at"
)

// WorkflowEdge property field names (BSON)
const (
	WorkflowEdgeId = "id"
	WorkflowEdgeSource = "source"
	WorkflowEdgeSourcePort = "sourcePort"
	WorkflowEdgeTarget = "target"
	WorkflowEdgeTargetPort = "targetPort"
	WorkflowEdgeCondition = "condition"
)

// WorkflowNode property field names (BSON)
const (
	WorkflowNodeId = "id"
	WorkflowNodeLabel = "label"
	WorkflowNodeX = "x"
	WorkflowNodeY = "y"
	WorkflowNodeStageRef = "stageRef"
	WorkflowNodeData = "data"
)

// WorkflowTrigger property field names (BSON)
const (
	WorkflowTriggerSelection = "selection"
	WorkflowTriggerStartAt = "startAt"
	WorkflowTriggerEndAt = "endAt"
	WorkflowTriggerWeekdays = "weekdays"
)
