// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// Workflow property field names (BSON)
const (
	WorkflowId = "_id"
	WorkflowName = "name"
	WorkflowDescription = "description"
	WorkflowEnabled = "enabled"
	WorkflowNodes = "nodes"
	WorkflowEdges = "edges"
	WorkflowUserId = "user_id"
	WorkflowUsername = "username"
	WorkflowMasterUserId = "master_user_id"
	WorkflowCreatedAt = "created_at"
	WorkflowUpdatedAt = "updated_at"
)

// WorkflowEdge property field names (BSON)
const (
	WorkflowEdgeId = "id"
	WorkflowEdgeSource = "source"
	WorkflowEdgeSourcePort = "sourcePort"
	WorkflowEdgeTarget = "target"
	WorkflowEdgeTargetPort = "targetPort"
)

// WorkflowNode property field names (BSON)
const (
	WorkflowNodeId = "id"
	WorkflowNodeType = "type"
	WorkflowNodeLabel = "label"
	WorkflowNodeX = "x"
	WorkflowNodeY = "y"
	WorkflowNodeSelection = "selection"
	WorkflowNodeStartAt = "startAt"
	WorkflowNodeEndAt = "endAt"
	WorkflowNodeWeekdays = "weekdays"
	WorkflowNodeData = "data"
)
