// Code generated by generate-properties. DO NOT EDIT.
// Source: pkg/models/*.go

package properties

// WorkflowRun property field names (BSON)
const (
	WorkflowRunId = "_id"
	WorkflowRunWorkflowId = "workflowid"
	WorkflowRunWorkflowName = "workflowname"
	WorkflowRunStages = "stages"
	WorkflowRunOrigin = "origin"
	WorkflowRunTriggerMatch = "triggermatch"
	WorkflowRunMatchedStartEdgeIds = "matchedstartedgeids"
	WorkflowRunSourceRef = "sourceref"
	WorkflowRunSourceType = "sourcetype"
	WorkflowRunKey = "key"
	WorkflowRunRecordingTimestamp = "recordingtimestamp"
	WorkflowRunOrganisationId = "organisationId"
	WorkflowRunProjectId = "projectId"
	WorkflowRunTraceId = "traceid"
	WorkflowRunStart = "start"
	WorkflowRunEnd = "end"
	WorkflowRunStageExecutions = "stageexecutions"
	WorkflowRunInputs = "inputs"
	WorkflowRunResults = "results"
	WorkflowRunDispatchedOperations = "dispatchedoperations"
	WorkflowRunResolvedOperations = "resolvedoperations"
)

// WorkflowRunStageExecution property field names (BSON)
const (
	WorkflowRunStageExecutionOperation = "operation"
	WorkflowRunStageExecutionName = "name"
	WorkflowRunStageExecutionDependencies = "dependencies"
	WorkflowRunStageExecutionDispatchAttempts = "dispatchattempts"
	WorkflowRunStageExecutionFirstDispatchAttemptAtMs = "firstdispatchattemptatms"
	WorkflowRunStageExecutionLastDispatchAttemptAtMs = "lastdispatchattemptatms"
	WorkflowRunStageExecutionDispatchedAtMs = "dispatchedatms"
	WorkflowRunStageExecutionResolvedAtMs = "resolvedatms"
	WorkflowRunStageExecutionLastDispatchErrorCode = "lastdispatcherrorcode"
)
