/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIMetadata: {
            error?: Record<string, never>;
            path?: string;
            /** Format: int64 */
            timestamp?: number;
            user_id?: string;
        };
        ErrorResponse: {
            error_code?: string;
            message?: string;
            meta_data?: components["schemas"]["APIMetadata"];
            request_id?: string;
            /** Format: int32 */
            status_code?: number;
        };
        Media: {
            deviceId?: string;
            /** Format: int64 */
            duration?: number;
            /** Format: int64 */
            endTimestamp?: number;
            groupId?: string;
            metadata?: components["schemas"]["MediaMetadata"][];
            organisationId?: string;
            spriteFile?: string;
            /** Format: int32 */
            spriteInterval?: number;
            spriteProvider?: string;
            spriteUrl?: string;
            /** Format: int64 */
            startTimestamp?: number;
            storageSolution?: string;
            thumbnailFile?: string;
            thumbnailProvider?: string;
            thumbnailUrl?: string;
            userId?: string;
            videoFile?: string;
            videoProvider?: string;
            videoUrl?: string;
        };
        MediaMetadata: {
            classifications?: string[];
            tags?: string[];
        };
        SuccessResponse: {
            message?: string;
            meta_data?: components["schemas"]["APIMetadata"];
            request_id?: string;
            /** Format: int32 */
            status_code?: number;
            success_code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
