name: Publish to NPM
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install dependencies
        working-directory: ./src/typescript
        run: npm ci
             
      - name: Generate types
        run: npm run generate
        
      - name: Build TypeScript
        working-directory: ./src/typescript
        run: npm run build
        
      - name: Update package version
        working-directory: ./src/typescript
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          RELEASE_VERSION=${RELEASE_VERSION#v}
          npm version $RELEASE_VERSION --no-git-tag-version
          
      - name: Publish to NPM
        working-directory: ./src/typescript
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}